" ----------------------------------------------------------------------
" Vundle
" ----------------------------------------------------------------------

set nocompatible " Be IMproved

call plug#begin('~/.vim/bundle')

" Bundles for code editing
Plug 'Raimondi/delimitMate'
Plug 'SirVer/ultisnips'
Plug 'Valloric/YouCompleteMe', { 'do': './install.sh --clang-completer' }
Plug 'honza/vim-snippets'
Plug 'scrooloose/syntastic'
Plug 'terryma/vim-multiple-cursors'
Plug 'tomtom/tcomment_vim'
Plug 'tpope/vim-surround'
Plug 'xuhdev/vim-latex-live-preview'

" Bundles that make life a HELL OF A LOT easier
Plug 'airblade/vim-gitgutter'
Plug 'derekwyatt/vim-protodef', { 'for': ['cpp', 'c', 'h','hpp'] }
Plug 'duff/vim-bufonly'
Plug 'Lokaltog/vim-easymotion'
Plug 'tpope/vim-fugitive'
Plug 'christoomey/vim-tmux-navigator'
Plug 'derekwyatt/vim-fswitch', { 'for': ['cpp', 'c', 'h', 'hpp'] }
Plug 'mattn/emmet-vim', { 'for': ['html', 'css', 'scss', 'sass', 'js', 'coffee'] }
Plug 'tpope/vim-abolish'
Plug 'mhinz/vim-startify'
Plug 'zhaocai/GoldenView.Vim', {'on': '<Plug>ToggleGoldenViewAutoResize'}
Plug 'oblitum/rainbow'
Plug 'junegunn/goyo.vim'

" Bundles for Unite
Plug 'Shougo/vimproc.vim', { 'do': 'make' }
Plug 'Shougo/neomru.vim'
Plug 'Shougo/unite.vim'

" Bundles for making stuff look better
Plug 'altercation/vim-colors-solarized'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'bling/vim-airline'
Plug 'othree/html5.vim', { 'for': 'html' }

" All the color schemes in the world!
Plug 'daylerees/colour-schemes'

call plug#end()

" Auto-loads matchit assuming user has not installed a newer version
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime! macros/matchit.vim
endif

" ----------------------------------------------------------------------
" moving around, searching and patterns
" ----------------------------------------------------------------------

set incsearch " Highlight pattern matches as you type
set ignorecase " Ignore case when using a search pattern
set smartcase " Override 'ignorecase' when pattern has upper case character
set gdefault " Defaults global argument in substitution command

" ----------------------------------------------------------------------
" tags
" ----------------------------------------------------------------------

" ----------------------------------------------------------------------
" displaying text
" ----------------------------------------------------------------------

set linebreak " For lines longer than the window, wrap intelligently

set colorcolumn=72 " Sets a colored column on column 72

set number " Precedes each line with a line number
set relativenumber " Fixes bug with relativenumber/number switch

set cmdheight=2 " Helps avoid 'Press ENTER...' prompts

" ----------------------------------------------------------------------
" syntax, highlighting and spelling
" ----------------------------------------------------------------------

syntax on " Enables Vim to show parts of the text in another font or color

set background=dark " Uses dark version of colorscheme

let g:solarized_termcolors=256 " Adds 256 color in terminal mode (specifically for solarized colorscheme)
colorscheme bubblegum " Sets colorscheme

set cursorline " Highlights current line cursor is on

if has("unix") " Checks to see if OS is mac or linux
  if system('uname') =~ 'Darwin' " If OS is Mac
    set guifont=Inconsolata\ for\ Powerline:h16
  else " If OS is Linux
    set guifont=Inconsolata\ for\ Powerline\ Medium\ 12
  endif
endif

" ----------------------------------------------------------------------
" multiple windows
" ----------------------------------------------------------------------

set laststatus=2 " Last window will always have a status line

set hidden " Allows switching buffers without saving
set splitright " Defaults splitting windows the right
set splitbelow " Default's splitting windows below

" ----------------------------------------------------------------------
" multiple tab pages
" ----------------------------------------------------------------------

" ----------------------------------------------------------------------
" terminal
" ----------------------------------------------------------------------

" set ttyfast "Faster screen-drawing

" ----------------------------------------------------------------------
" using the mouse
" ----------------------------------------------------------------------

" ----------------------------------------------------------------------
" GUI
" ----------------------------------------------------------------------

if has('gui_running')
  set guioptions-=T
  set guioptions-=R
  set guioptions-=r
  set guioptions-=l
  set guioptions-=L
endif

" ----------------------------------------------------------------------
" printing
" ----------------------------------------------------------------------

" ----------------------------------------------------------------------
" messages and info
" ----------------------------------------------------------------------

set noshowmode

" ----------------------------------------------------------------------
" selecting text
" ----------------------------------------------------------------------

" ----------------------------------------------------------------------
" editing text
" ----------------------------------------------------------------------
filetype plugin indent on

set backspace=indent,eol,start " Makes backspace behave like most editors

set textwidth=72 " Sets wrapping point at 72 characters

set formatoptions=cqn

if v:version > 703 || v:version == 703 && has("patch541")
  set formatoptions+=j          " Delete comment char on second line when
    " Joining two commented lines
endif

function! <SID>StripTrailingWhitespaces()
  " Preparation: save last search, and cursor position.
  let l = line(".")
  let c = col(".")
  " Do the business:
  %s/\s\+$//e
  " Clean up: restore previous search history, and
  " cursor position
  call cursor(l, c)
endfunction

" ----------------------------------------------------------------------
" tabs and indenting
" ----------------------------------------------------------------------

set tabstop=2 " Tab=2 spaces
set shiftwidth=2 " Auto-indents 2 spaces
set smarttab " Tab in front of a line inserts 'shiftwidth' spaces
set shiftround " Round to 'shiftwidth' for << and >>
set expandtab " Tabs insert 'tabstop' spaces instead of one tab
set autoindent " Better indentation

set pastetoggle=<F3> " Toggles smart indenting while pasting, A.K.A lifesaver

" ----------------------------------------------------------------------
" folding
" ----------------------------------------------------------------------

" ----------------------------------------------------------------------
" diff mode
" ----------------------------------------------------------------------

" ----------------------------------------------------------------------
" mapping
" ----------------------------------------------------------------------

let mapleader = ","

" netrw
nnoremap <leader>n :e .<CR>

vnoremap > >gv
vnoremap < <gv

" Open vimrc file in a new tab for editing
nnoremap <leader>ev :tabe ~/.dotfiles/files/vimrc<CR>

" Open current file in Chrome
nnoremap <leader>o :!google-chrome-beta %<CR>

" Save file
nnoremap <leader>w :w<CR>

" Delete current buffer
nnoremap <leader>d :bd %<CR>

" Makes saving a little easier :P
nnoremap ; :

" Trim whitespace, yay!
nnoremap <silent> <leader>W :call <SID>StripTrailingWhitespaces()<CR>

" Thank god, no more ESC key
inoremap jk <ESC>

" Better line navigation
nnoremap j gj
nnoremap k gk

" Easy window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Forgot to sudo? No problem ;)
cmap w!! w !sudo tee % >/dev/null

" Run C++ skeleton compile
noremap <leader>c !./compile

" Run C++ skeleton compile and test
noremap <leader>ct !./run_tests

" YouCompleteMe
nnoremap <leader>jd :YcmCompleter GoToDefinitionElseDeclaration<CR>

" BufOnly mappings
nnoremap <leader>da :BufOnly<CR>
"
" Fugitive mappings
nnoremap <silent> <leader>gs :Gstatus<CR>
nnoremap <silent> <leader>gd :Gdiff<CR>
nnoremap <silent> <leader>gc :Gcommit
nnoremap <silent> <leader>gb :Gblame<CR>
nnoremap <silent> <leader>gl :Glog<CR>
nnoremap <silent> <leader>gp :Git push<CR>

" Fswitch mappings
nnoremap <leader>fs :FSHere<CR>
nnoremap <leader>fsr :FSSplitRight<CR>
nnoremap <leader>fsl :FSSplitLeft<CR>

" Latex mappings
nnoremap <leader>lb :!rubber --inplace --pdf %<CR> :!rubber --inplace --clean %<CR>
nnoremap <leader>lv :!evince %:r.pdf > /dev/null 2>&1 &<CR><CR>
nnoremap <leader>lbv :!rubber --inplace --pdf %<CR> :!rubber --inplace --clean %<CR> :!evince %:r.pdf > /dev/null 2>&1 &<CR><CR>

" Unite mappings
nnoremap <C-P> :<C-u>Unite  -buffer-name=files      -start-insert file_rec/async<CR>
nnoremap <leader>f :<C-u>Unite -buffer-name=files   -start-insert file<CR>
nnoremap <leader>y :<C-u>Unite -buffer-name=yank    history/yank<CR>
nnoremap <leader>b :<C-u>Unite -buffer-name=buffer  buffer<CR>
nnoremap <leader>r :<C-u>Unite -buffer-name=mru     -start-insert file_mru<CR>

" GoldenView.vim mappings
nmap <F4> <Plug>ToggleGoldenViewAutoResize

" Goyo.vim
nnoremap <leader>g :Goyo<CR>

" ----------------------------------------------------------------------
" reading and writing files
" ----------------------------------------------------------------------

set autoread "re-reads file changed outside of vim

" ----------------------------------------------------------------------
" the swap file
" ----------------------------------------------------------------------

set nobackup
set noswapfile

" ----------------------------------------------------------------------
" command line editing
" ----------------------------------------------------------------------

set history=200 " Save more commands in history

set wildmode=longest,full " see :help wildmode for options

" Makes wild menu ignore these file types
set wildignore+=*.exe,*.swp,.DS_Store
set wildmenu

if exists('&wildignorecase')
  set wildignorecase
endif

" ----------------------------------------------------------------------
" executing external commands
" ----------------------------------------------------------------------

" ----------------------------------------------------------------------
" running make and jumping to errors
" ----------------------------------------------------------------------

" ----------------------------------------------------------------------
" language specific
" ----------------------------------------------------------------------

" ----------------------------------------------------------------------
" multi-byte characters
" ----------------------------------------------------------------------

set encoding=utf-8 " C'mon, this is obvious

" ----------------------------------------------------------------------
" Plugin Settings
" ----------------------------------------------------------------------

" DelimitMate
let g:delimitMate_expand_cr = 1
let g:delimitMate_expand_space = 1

" YouCompleteMe
let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_min_num_of_chars_for_completion = 1

" Ultisnips
let g:UltiSnipsEditSplit = 'vertical'
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<S-tab>"
let g:UltiSnipsListSnippets="<c-e>"

" Syntastic
let g:syntastic_cpp_compiler = 'clang++'
let g:syntastic_cpp_compiler_options = '-std=c++11 -stdlib=libc++'
let g:syntastic_php_checkers=['php', 'phpmd']
let g:syntastic_check_on_open=1

" netrw
let g:netrw_preview=1
let g:netrw_special_syntax=1
let g:netrw_banner=0

" vim-airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" Unite
let g:unite_enable_start_insert = 1
let g:unite_force_overwrite_statusline = 0
let g:unite_winheight = 10

call unite#custom_source('file_rec,file_rec/async,file_mru,file,buffer,grep',
      \ 'ignore_pattern', join([
      \ '\.git/',
      \ ], '\|'))

call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])

" Emmet
let g:user_emmet_leader_key='<C-e>'

" vim-startify
let g:startify_session_dir = '~/.vim/.cache/sessions'
let g:startify_change_to_vcs_root = 1
let g:startify_show_sessions = 1

" GoldenView.vim
let g:goldenview__enable_default_mapping=0

" Rainbow
au FileType c,cpp,objc,objcpp,python,javascript call rainbow#load()

" ----------------------------------------------------------------------
" various
" ----------------------------------------------------------------------

" ----------------------------------------------------------------------
" Functions
" ----------------------------------------------------------------------

function! g:UltiSnips_Complete()
  call UltiSnips#ExpandSnippetOrJump()
  if g:ulti_expand_or_jump_res == 0
    if pumvisible()
      return "\<c-n>"
    else
      return "\<tab>"
    endif
  endif

  return ""
endfunction

function! s:unite_settings()
  imap <buffer> <C-j>   <Plug>(unite_select_next_line)
  imap <buffer> <C-k>   <Plug>(unite_select_previous_line)
  imap <silent><buffer><expr> <C-x> unite#do_action('split')
  imap <silent><buffer><expr> <C-v> unite#do_action('vsplit')
  imap <silent><buffer><expr> <C-t> unite#do_action('tabopen')

  nmap <buffer> <ESC> <Plug>(unite_exit)
endfunction

" ----------------------------------------------------------------------
" Autocmds
" ----------------------------------------------------------------------

augroup formatting
  autocmd!
  autocmd FileType markdown,mkd,txt,gitcommit,tex setlocal formatoptions+=t
  autocmd FileType markdown,mkd,txt,gitcommit,tex setlocal spell
  autocmd FileType markdown,mkd,txt,tex :Goyo
augroup END

augroup relativenumber
  autocmd!
  autocmd InsertEnter,focusLost * :set norelativenumber
  autocmd InsertLeave,focusGained * :set relativenumber
augroup END

" Better integration between YouCompleteMe and UltiSnips
autocmd BufEnter * exec "inoremap <buffer> <silent> " . g:UltiSnipsExpandTrigger . " <c-r>=g:UltiSnips_Complete()<CR>"

" Custom mappings for the unite buffer
autocmd FileType unite call s:unite_settings()
