#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Make life easier to use
alias vi="nvim"
alias open="xdg-open"

export NVM_DIR="/home/michael/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
source "/etc/profile.d/rvm.sh"

# Customize to your needs...
export WORKON_HOME="$HOME/.virtualenvs"
export XDG_CONFIG_HOME="$HOME/.config"

export NVM_DIR="/home/michael/.nvm"

# NPM without sudo
NPM_PACKAGES="${HOME}/.npm-packages"
export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
# Unset manpath so we can inherit from /etc/manpath via the `manpath`
# command
unset MANPATH # delete if you already modified MANPATH elsewhere in your config
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"
export PATH="$(python3 -c 'import site; print(site.USER_BASE)')/bin:$PATH"
export PATH="$(ruby -e 'print Gem.user_dir')/bin:$HOME/.rvm/bin:$PATH"
export PATH="$NPM_PACKAGES/bin:$HOME/Documents/scripts:$PATH"
